spring:
    application:
        name: workshop
    datasource:
        url: jdbc:sqlite:database/store.db
        driver-class-name: org.sqlite.JDBC
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.community.dialect.SQLiteDialect
        show-sql: true
        properties:
            hibernate:
                format-sql: true
    output:
        ansi:
            enabled: always
    # sql:
    #     init:
    #         mode: always
    #         data-locations: classpath:data.sql
# logging:
#     level:
#         org:
#             springframework:
#                 transaction: DEBUG
#             hibernate:
#                 SQL: DEBUG
#                 type:
#                     descriptor:
#                         sql:
#                             BasicBinder: TRACE
