{
  "openapi": "3.0.1",
  "info":
    {
      "title": "Store Backend Server",
      "description": "Spring Boot backend for store application",
      "contact":
        {
          "name": "Full Stack K-Tech Community",
          "url": "https://www.klx.pt/",
          "email": "orlando.santos@klx.com",
        },
      "version": "1.0.0",
    },
  "servers":
    [{ "url": "http://localhost:8080", "description": "Local Environment" }],
  "paths":
    {
      "/api/cart-items":
        {
          "get":
            {
              "tags": ["cart-item-controller"],
              "operationId": "showProductsInCartItem",
              "responses":
                {
                  "200":
                    {
                      "description": "OK",
                      "content":
                        {
                          "*/*":
                            {
                              "schema":
                                {
                                  "type": "array",
                                  "items":
                                    {
                                      "$ref": "#/components/schemas/ProductCartItemDTO",
                                    },
                                },
                            },
                        },
                    },
                },
            },
          "post":
            {
              "tags": ["cart-item-controller"],
              "operationId": "addProductToCartItem",
              "requestBody":
                {
                  "content":
                    {
                      "application/json":
                        {
                          "schema":
                            { "$ref": "#/components/schemas/ProductDTO" },
                        },
                    },
                  "required": true,
                },
              "responses":
                {
                  "200":
                    {
                      "description": "OK",
                      "content":
                        {
                          "*/*":
                            {
                              "schema":
                                {
                                  "type": "array",
                                  "items":
                                    {
                                      "$ref": "#/components/schemas/ProductCartItemDTO",
                                    },
                                },
                            },
                        },
                    },
                },
            },
        },
      "/api/products":
        {
          "get":
            {
              "tags": ["product-controller"],
              "operationId": "findAll",
              "responses":
                {
                  "200":
                    {
                      "description": "OK",
                      "content":
                        {
                          "*/*":
                            {
                              "schema":
                                {
                                  "type": "array",
                                  "items":
                                    {
                                      "$ref": "#/components/schemas/ProductDTO",
                                    },
                                },
                            },
                        },
                    },
                },
            },
        },
      "/api/products/{id}":
        {
          "get":
            {
              "tags": ["product-controller"],
              "operationId": "findById",
              "parameters":
                [
                  {
                    "name": "id",
                    "in": "path",
                    "required": true,
                    "schema": { "type": "integer", "format": "int64" },
                  },
                ],
              "responses":
                {
                  "200":
                    {
                      "description": "OK",
                      "content":
                        {
                          "*/*":
                            {
                              "schema":
                                { "$ref": "#/components/schemas/ProductDTO" },
                            },
                        },
                    },
                },
            },
        },
      "/api/cart-items/{id}":
        {
          "delete":
            {
              "tags": ["cart-item-controller"],
              "operationId": "deleteProductFromCartItem",
              "parameters":
                [
                  {
                    "name": "id",
                    "in": "path",
                    "required": true,
                    "schema": { "type": "integer", "format": "int64" },
                  },
                ],
              "responses":
                {
                  "200":
                    {
                      "description": "OK",
                      "content":
                        {
                          "*/*":
                            {
                              "schema":
                                {
                                  "type": "array",
                                  "items":
                                    {
                                      "$ref": "#/components/schemas/ProductCartItemDTO",
                                    },
                                },
                            },
                        },
                    },
                },
            },
        },
    },
  "components":
    {
      "schemas":
        {
          "ProductDTO":
            {
              "type": "object",
              "properties":
                {
                  "id": { "type": "integer", "format": "int64" },
                  "name": { "type": "string" },
                  "description": { "type": "string" },
                  "price": { "type": "number", "format": "double" },
                  "discount": { "type": "number", "format": "double" },
                  "favorite": { "type": "boolean" },
                  "imageBase64": { "type": "string" },
                },
            },
          "ProductCartItemDTO":
            {
              "type": "object",
              "properties":
                {
                  "product": { "$ref": "#/components/schemas/ProductDTO" },
                  "quantity": { "type": "integer", "format": "int32" },
                },
            },
        },
    },
}
